laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('about-us', ['as' => 'about', 'uses' => 'NosController@index']);

Route::get('portfolio/{categoria_slug?}', [
    'as'   => 'portfolio',
    'uses' => 'CatalogoController@index'
]);
Route::get('portfolio/{categoria_slug}/{filme_slug}', [
    'as'   => 'portfolio.show',
    'uses' => 'CatalogoController@show'
]);

Route::get('clients', ['as' => 'clients', 'uses' => 'ClientesController@index']);

Route::get('news', ['as' => 'news', 'uses' => 'NovidadesController@index']);
Route::get('news/{slug}', ['as' => 'news.show', 'uses' => 'NovidadesController@show']);

Route::get('contact', ['as' => 'contact', 'uses' => 'ContatoController@index']);
Route::post('contact', ['as' => 'contact.send', 'uses' => 'ContatoController@send']);


// Painel

Route::get('painel', [
    'before' => 'auth',
        'as' => 'painel.home',
      'uses' => 'Painel\HomeController@index'
]);

Route::get('painel/login', ['as' => 'painel.login', 'uses' => 'Painel\HomeController@login']);
Route::post('painel/login', ['as' => 'painel.auth', 'uses' => 'Painel\HomeController@attempt']);
Route::get('painel/logout', ['as' => 'painel.logout', 'uses' => 'Painel\HomeController@logout']);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::resource('banners', 'Painel\BannersController');
    Route::resource('cabecalhos', 'Painel\CabecalhosController');
    Route::resource('nos', 'Painel\NosController');
    Route::resource('catalogo', 'Painel\CatalogoCategoriasController');
    Route::resource('catalogo.filmes', 'Painel\CatalogoFilmesController');
    Route::resource('clientes', 'Painel\ClientesController');
    Route::resource('novidades', 'Painel\NovidadesController');
    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::post('ajax/order', 'Painel\AjaxController@order');
});

laravel/app/controllers/painel/AjaxController.php
<?php

namespace Painel;

use \Request, \Input, \DB, \Controller;

class AjaxController extends Controller {

    function order()
    {

        if (!Request::ajax()) return false;

        $menu   = Input::get('data');
        $tabela = Input::get('tabela');

        for ($i = 0; $i < count($menu); $i++) {
            DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
        }

        return json_encode($menu);

    }

}

laravel/app/controllers/painel/BannersController.php
<?php

namespace Painel;

use \Banner, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class BannersController extends BasePainelController {

    private $validation_rules = [
        'link'   => 'required',
        'imagem' => 'required|image'
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return $this->view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return $this->view('painel.banners.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', [
                'width'  => 1920,
                'height' => 645,
                'path'   => 'assets/img/banners/'
            ]);
            Banner::create($input);
            Session::flash('sucesso', 'Banner criado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return var_dump($e);
            return Redirect::back()
                ->withErrors(['Erro ao criar banner.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $banner = Banner::findOrFail($id);

        return $this->view('painel.banners.edit', compact('banner'));
    }

    public function update($id)
    {
        $banner = Banner::findOrFail($id);
        $input  = Input::all();

        $this->validation_rules['imagem'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', [
                    'width'  => 1920,
                    'height' => 645,
                    'path'   => 'assets/img/banners/'
                ]);
            } else {
                unset($input['imagem']);
            }

            $banner->update($input);
            Session::flash('sucesso', 'Banner alterado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            dd($e);

            return Redirect::back()
                ->withErrors(['Erro ao alterar banner.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            banner::destroy($id);
            Session::flash('sucesso', 'Banner removido com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover banner.']);

        }
    }

}

laravel/app/controllers/painel/BasePainelController.php
<?php

namespace Painel;

use \View, \ContatoRecebido;

class BasePainelController extends \Controller {

    protected $layout = 'painel.common.template';

    protected function setupLayout()
    {
        if ( ! is_null($this->layout))
        {
            $recebidos_count = ContatoRecebido::naoLidos()->count();
            View::share(compact('recebidos_count'));
            $this->layout = View::make($this->layout);
        }
    }

    protected function view($path, array $data = [])
    {
        $this->layout->content = View::make($path, $data);
    }

}

laravel/app/controllers/painel/CabecalhosController.php
<?php

namespace Painel;

use \Cabecalho, \Input, \Validator, \Session, \Redirect, \CropImage;

class CabecalhosController extends BasePainelController {


    protected $validation_rules = [
        'nos'       => 'image',
        'catalogo'  => 'image',
        'clientes'  => 'image',
        'novidades' => 'image',
        'contato'   => 'image'
    ];

    protected $image_config = [
        'width'  => 1920,
        'height' => 245,
        'path'   => 'assets/img/cabecalhos/'
    ];

    public function index()
    {
        $cabecalhos = Cabecalho::first();

        return $this->view('painel.cabecalhos.index', compact('cabecalhos'));
    }

    public function update($id)
    {
        $cabecalho = Cabecalho::findOrFail($id);
        $input     = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            foreach ($input as $key => $value) {
                if (Input::hasFile($key)) {
                    $input[$key] = CropImage::make($key, $this->image_config);
                } else {
                    unset($input[$key]);
                }
            }

            $cabecalho->update($input);
            Session::flash('sucesso', 'Imagens alteradas com sucesso.');

            return Redirect::route('painel.cabecalhos.index');

        } catch (\Exception $e) {

            dd($e);

            return Redirect::back()
                ->withErrors(['Erro ao alterar imagens.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/CatalogoCategoriasController.php
<?php

namespace Painel;

use \CatalogoCategoria, \View, \Input, \Session, \Redirect, \Validator, \Str, \CropImage;

class CatalogoCategoriasController extends BasePainelController {

    protected $validation_rules = [
        'titulo' => 'required'
    ];

    public function index()
    {
        $categorias = CatalogoCategoria::ordenados()->get();

        return $this->view('painel.catalogo.index', compact('categorias'));
    }

    public function create()
    {
        return $this->view('painel.catalogo.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));

            CatalogoCategoria::create($input);
            Session::flash('sucesso', 'Categoria criada com sucesso.');

            return Redirect::route('painel.catalogo.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar categoria. Verifique se já existe outra categoria com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $categoria = CatalogoCategoria::findOrFail($id);

        return $this->view('painel.catalogo.edit', compact('categoria'));
    }

    public function update($id)
    {
        $categoria = CatalogoCategoria::findOrFail($id);
        $input     = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));

            $categoria->update($input);
            Session::flash('sucesso', 'Categoria alterada com sucesso.');

            return Redirect::route('painel.catalogo.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar categoria. Verifique se já existe outra categoria com o mesmo título.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            CatalogoCategoria::destroy($id);
            Session::flash('sucesso', 'Categoria removida com sucesso.');

            return Redirect::route('painel.catalogo.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover categoria.']);

        }
    }

}

laravel/app/controllers/painel/CatalogoFilmesController.php
<?php

namespace Painel;

use \CatalogoFilme, \CatalogoCategoria, \View, \Input, \Session, \Redirect, \Validator, \Str, \CropImage;

class CatalogoFilmesController extends BasePainelController {

    protected $validation_rules = [
        'titulo'        => 'required',
        'olho'          => 'required',
        'descricao'     => 'required',
        'ficha_tecnica' => 'required',
        'poster'        => 'required|image',
        'capa'          => 'required|image',
    ];

    protected $image_config = [
        'capa' => [
            'width'  => 675,
            'height' => 450,
            'path'   => 'assets/img/catalogo/'
        ],
        'poster' => [
            'width'  => 340,
            'height' => 510,
            'path'   => 'assets/img/catalogo/poster/'
        ]
    ];

    public function index($categoria_id)
    {
        $categoria = CatalogoCategoria::findOrFail($categoria_id);
        $filmes    = CatalogoFilme::categoria($categoria_id)->ordenados()->get();

        return $this->view('painel.catalogo.filmes.index', compact(['filmes', 'categoria']));
    }

    public function create($categoria_id)
    {
        $categoria = CatalogoCategoria::findOrFail($categoria_id);

        return $this->view('painel.catalogo.filmes.create', compact('categoria'));
    }

    public function store($categoria_id)
    {
        $categoria = CatalogoCategoria::findOrFail($categoria_id);
        $input     = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));
            $input['categoria_id'] = $categoria->id;

            $input['poster'] = CropImage::make('poster', $this->image_config['poster']);
            $input['capa']   = CropImage::make('capa', $this->image_config['capa']);

            if (Input::has('mostrar_home')) {
                $input['mostrar_home'] = true;
            } else {
                $input['mostrar_home'] = false;
            }

            CatalogoFilme::create($input);
            Session::flash('sucesso', 'Filme criado com sucesso.');

            return Redirect::route('painel.catalogo.filmes.index', $categoria->id);

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar filme. Verifique se já existe outro filme com o mesmo título.'])
                ->withInput();

        }
    }

    public function edit($categoria_id, $filme_id)
    {
        $categoria = CatalogoCategoria::findOrFail($categoria_id);
        $filme     = CatalogoFilme::findOrFail($filme_id);

        return $this->view('painel.catalogo.filmes.edit', compact(['categoria', 'filme']));
    }

    public function update($categoria_id, $filme_id)
    {
        $categoria = CatalogoCategoria::findOrFail($categoria_id);
        $filme     = CatalogoFilme::findOrFail($filme_id);
        $input     = Input::all();

        $this->validation_rules['poster'] = 'image';
        $this->validation_rules['capa'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['slug'] = Str::slug(Input::get('titulo'));
            $input['categoria_id'] = $categoria->id;

            if (Input::hasFile('poster')) {
                $input['poster'] = CropImage::make('poster', $this->image_config['poster']);
            } else {
                unset($input['poster']);
            }

            if (Input::hasFile('capa')) {
                $input['capa'] = CropImage::make('capa', $this->image_config['capa']);
            } else {
                unset($input['capa']);
            }

            if (Input::has('mostrar_home')) {
                $input['mostrar_home'] = true;
            } else {
                $input['mostrar_home'] = false;
            }

            $filme->update($input);
            Session::flash('sucesso', 'Filme alterado com sucesso.');

            return Redirect::route('painel.catalogo.filmes.index', $categoria->id);

        } catch (\Exception $e) {

            return $e;

            return Redirect::back()
                ->withErrors(['Erro ao alterar filme. Verifique se já existe outro filme com o mesmo título.'])
                ->withInput();

        }
    }

    public function destroy($categoria_id, $filme_id)
    {
        $categoria = CatalogoCategoria::findOrFail($categoria_id);

        try {

            CatalogoFilme::destroy($filme_id);
            Session::flash('sucesso', 'Filme removido com sucesso.');

            return Redirect::route('painel.catalogo.filmes.index', $categoria_id);

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover filme.']);

        }
    }

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use \Contato, \Input, \Session, \Redirect, \Validator;

class ContatoController extends BasePainelController {

    private $validation_rules = [
        'email' => 'required|email'
    ];

    public function index()
    {
    	$contato = Contato::first();

        return $this->view('painel.contato.index', compact('contato'));
    }

    public function update($id)
    {
        $contato = Contato::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $contato->update($input);
            Session::flash('sucesso', 'Informações de contato alteradas com sucesso.');

            return Redirect::route('painel.contato.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações de contato.'])
                ->withInput();

        }
    }

}

laravel/app/views/painel/common/nav.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url() }}">{{ Config::get('projeto.titulo') }}</a>
        </div>

    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li @if(str_is('painel.banners*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.banners.index') }}">Banners</a>
            </li>

            <li @if(str_is('painel.cabecalhos*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.cabecalhos.index') }}">Cabeçalhos</a>
            </li>

            <li @if(str_is('painel.nos*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.nos.index') }}">Nós</a>
            </li>

            <li @if(str_is('painel.catalogo*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.catalogo.index') }}">Catálogo</a>
            </li>

            <li @if(str_is('painel.clientes*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.clientes.index') }}">Clientes</a>
            </li>

            <li @if(str_is('painel.novidades*',Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.novidades.index') }}">Novidades</a>
            </li>

            <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contato @if($recebidos_count>=1)<span class="badge">{{ $recebidos_count }}</span>@endif <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
                    <li><a href="{{ route('painel.contato.recebidos.index') }}">Contatos Recebidos @if($recebidos_count>=1)<span class="badge">{{ $recebidos_count }}</span>@endif</a></li>
                </ul>
            </li>

            <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                    <li><a href="{{ route('painel.logout') }}">Logout</a></li>
                </ul>
            </li>
        </ul>
    </div>
    </div>
</nav>

laravel/app/views/painel/common/template.blade.php
<?php $login = (Route::currentRouteName() == 'painel.login'); ?>
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ Config::get('projeto.titulo') }} - Painel Administrativo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url('assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url('assets/css/bootstrap-theme.min.css') }}">
    <link rel="stylesheet" href="{{ url('assets/css/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ url('assets/css/painel.min.css') }}">

    <script>var BASE = '{{ url() }}'</script>
</head>
<body class="{{ ($login ? 'login' : 'painel') }}">
    @if(!$login)
        @include('painel.common.nav')
    @endif

    <div class="{{ ($login ? 'wrapper' : 'main container') }}">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/assets/js/jquery.min.js"><\/script>')</script>
    <script src="{{ url('assets/js/jquery-ui.min.js') }}"></script>
    <script src="{{ url('assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ url('assets/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ url('assets/js/painel.js') }}"></script>
</body>
</html>